// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/plugin-generator/v1/plugin_service.proto

package plugingeneratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginGeneratorService_GenerateCode_FullMethodName = "/plugin_generator.v1.PluginGeneratorService/GenerateCode"
)

// PluginGeneratorServiceClient is the client API for PluginGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для обработки запросов генерации кода плагинов
type PluginGeneratorServiceClient interface {
	// Метод для генерации кода на основе запроса и информации о плагине
	GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error)
}

type pluginGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginGeneratorServiceClient(cc grpc.ClientConnInterface) PluginGeneratorServiceClient {
	return &pluginGeneratorServiceClient{cc}
}

func (c *pluginGeneratorServiceClient) GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCodeResponse)
	err := c.cc.Invoke(ctx, PluginGeneratorService_GenerateCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginGeneratorServiceServer is the server API for PluginGeneratorService service.
// All implementations should embed UnimplementedPluginGeneratorServiceServer
// for forward compatibility.
//
// Сервис для обработки запросов генерации кода плагинов
type PluginGeneratorServiceServer interface {
	// Метод для генерации кода на основе запроса и информации о плагине
	GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error)
}

// UnimplementedPluginGeneratorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginGeneratorServiceServer struct{}

func (UnimplementedPluginGeneratorServiceServer) GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCode not implemented")
}
func (UnimplementedPluginGeneratorServiceServer) testEmbeddedByValue() {}

// UnsafePluginGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginGeneratorServiceServer will
// result in compilation errors.
type UnsafePluginGeneratorServiceServer interface {
	mustEmbedUnimplementedPluginGeneratorServiceServer()
}

func RegisterPluginGeneratorServiceServer(s grpc.ServiceRegistrar, srv PluginGeneratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedPluginGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginGeneratorService_ServiceDesc, srv)
}

func _PluginGeneratorService_GenerateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginGeneratorServiceServer).GenerateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginGeneratorService_GenerateCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginGeneratorServiceServer).GenerateCode(ctx, req.(*GenerateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginGeneratorService_ServiceDesc is the grpc.ServiceDesc for PluginGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin_generator.v1.PluginGeneratorService",
	HandlerType: (*PluginGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCode",
			Handler:    _PluginGeneratorService_GenerateCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/plugin-generator/v1/plugin_service.proto",
}
