// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/plugin-generator/v1/plugin_service.proto

package plugingeneratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pluginpb "google.golang.org/protobuf/types/pluginpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос для генерации кода
type GenerateCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Запрос генератора кода из protoc
	CodeGeneratorRequest *pluginpb.CodeGeneratorRequest `protobuf:"bytes,1,opt,name=code_generator_request,json=codeGeneratorRequest,proto3" json:"code_generator_request,omitempty"`
	// Информация о плагине в формате "name:version" (например, "python:v32.1")
	PluginInfo    string `protobuf:"bytes,2,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCodeRequest) Reset() {
	*x = GenerateCodeRequest{}
	mi := &file_api_plugin_generator_v1_plugin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeRequest) ProtoMessage() {}

func (x *GenerateCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_generator_v1_plugin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_generator_v1_plugin_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCodeRequest) GetCodeGeneratorRequest() *pluginpb.CodeGeneratorRequest {
	if x != nil {
		return x.CodeGeneratorRequest
	}
	return nil
}

func (x *GenerateCodeRequest) GetPluginInfo() string {
	if x != nil {
		return x.PluginInfo
	}
	return ""
}

// Ответ сервиса генерации кода
type GenerateCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Результат генерации кода
	CodeGeneratorResponse *pluginpb.CodeGeneratorResponse `protobuf:"bytes,1,opt,name=code_generator_response,json=codeGeneratorResponse,proto3" json:"code_generator_response,omitempty"`
	// Статус обработки
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Дополнительные сообщения или ошибки
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCodeResponse) Reset() {
	*x = GenerateCodeResponse{}
	mi := &file_api_plugin_generator_v1_plugin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeResponse) ProtoMessage() {}

func (x *GenerateCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_generator_v1_plugin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_generator_v1_plugin_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCodeResponse) GetCodeGeneratorResponse() *pluginpb.CodeGeneratorResponse {
	if x != nil {
		return x.CodeGeneratorResponse
	}
	return nil
}

func (x *GenerateCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_plugin_generator_v1_plugin_service_proto protoreflect.FileDescriptor

const file_api_plugin_generator_v1_plugin_service_proto_rawDesc = "" +
	"\n" +
	",api/plugin-generator/v1/plugin_service.proto\x12\x13plugin_generator.v1\x1a%google/protobuf/compiler/plugin.proto\"\x9c\x01\n" +
	"\x13GenerateCodeRequest\x12d\n" +
	"\x16code_generator_request\x18\x01 \x01(\v2..google.protobuf.compiler.CodeGeneratorRequestR\x14codeGeneratorRequest\x12\x1f\n" +
	"\vplugin_info\x18\x02 \x01(\tR\n" +
	"pluginInfo\"\xb1\x01\n" +
	"\x14GenerateCodeResponse\x12g\n" +
	"\x17code_generator_response\x18\x01 \x01(\v2/.google.protobuf.compiler.CodeGeneratorResponseR\x15codeGeneratorResponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2}\n" +
	"\x16PluginGeneratorService\x12c\n" +
	"\fGenerateCode\x12(.plugin_generator.v1.GenerateCodeRequest\x1a).plugin_generator.v1.GenerateCodeResponseBUZSgithub.com/easyp-tech/easyp-plugin-server/api/plugin-generator/v1;plugingeneratorv1b\x06proto3"

var (
	file_api_plugin_generator_v1_plugin_service_proto_rawDescOnce sync.Once
	file_api_plugin_generator_v1_plugin_service_proto_rawDescData []byte
)

func file_api_plugin_generator_v1_plugin_service_proto_rawDescGZIP() []byte {
	file_api_plugin_generator_v1_plugin_service_proto_rawDescOnce.Do(func() {
		file_api_plugin_generator_v1_plugin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_plugin_generator_v1_plugin_service_proto_rawDesc), len(file_api_plugin_generator_v1_plugin_service_proto_rawDesc)))
	})
	return file_api_plugin_generator_v1_plugin_service_proto_rawDescData
}

var file_api_plugin_generator_v1_plugin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_plugin_generator_v1_plugin_service_proto_goTypes = []any{
	(*GenerateCodeRequest)(nil),            // 0: plugin_generator.v1.GenerateCodeRequest
	(*GenerateCodeResponse)(nil),           // 1: plugin_generator.v1.GenerateCodeResponse
	(*pluginpb.CodeGeneratorRequest)(nil),  // 2: google.protobuf.compiler.CodeGeneratorRequest
	(*pluginpb.CodeGeneratorResponse)(nil), // 3: google.protobuf.compiler.CodeGeneratorResponse
}
var file_api_plugin_generator_v1_plugin_service_proto_depIdxs = []int32{
	2, // 0: plugin_generator.v1.GenerateCodeRequest.code_generator_request:type_name -> google.protobuf.compiler.CodeGeneratorRequest
	3, // 1: plugin_generator.v1.GenerateCodeResponse.code_generator_response:type_name -> google.protobuf.compiler.CodeGeneratorResponse
	0, // 2: plugin_generator.v1.PluginGeneratorService.GenerateCode:input_type -> plugin_generator.v1.GenerateCodeRequest
	1, // 3: plugin_generator.v1.PluginGeneratorService.GenerateCode:output_type -> plugin_generator.v1.GenerateCodeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_plugin_generator_v1_plugin_service_proto_init() }
func file_api_plugin_generator_v1_plugin_service_proto_init() {
	if File_api_plugin_generator_v1_plugin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugin_generator_v1_plugin_service_proto_rawDesc), len(file_api_plugin_generator_v1_plugin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_plugin_generator_v1_plugin_service_proto_goTypes,
		DependencyIndexes: file_api_plugin_generator_v1_plugin_service_proto_depIdxs,
		MessageInfos:      file_api_plugin_generator_v1_plugin_service_proto_msgTypes,
	}.Build()
	File_api_plugin_generator_v1_plugin_service_proto = out.File
	file_api_plugin_generator_v1_plugin_service_proto_goTypes = nil
	file_api_plugin_generator_v1_plugin_service_proto_depIdxs = nil
}
