// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.17.0-bufbuild-protocompile-easyp
// source: easyp/generator/v1/generator.proto

package generator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeneratorAPI_GenerateCode_FullMethodName = "/easyp.generator.v1.GeneratorAPI/GenerateCode"
	GeneratorAPI_Plugins_FullMethodName      = "/easyp.generator.v1.GeneratorAPI/Plugins"
	GeneratorAPI_CreatePlugin_FullMethodName = "/easyp.generator.v1.GeneratorAPI/CreatePlugin"
	GeneratorAPI_UpdatePlugin_FullMethodName = "/easyp.generator.v1.GeneratorAPI/UpdatePlugin"
	GeneratorAPI_DeletePlugin_FullMethodName = "/easyp.generator.v1.GeneratorAPI/DeletePlugin"
)

// GeneratorAPIClient is the client API for GeneratorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # EasyP Code Generation Service
//
// This service provides a centralized API for executing protobuf/gRPC code generation plugins.
// Plugins are executed by the service, so every caller uses the same plugin version.
//
// ## Benefits
//
// - **Version Control**: All developers use the same plugin versions
// - **Zero Setup**: No local plugin installation required
// - **Auditability**: Centralized logging of all generation requests
//
// ## How plugins are executed
//
// A plugin is a binary the service runs as a local child process. It is not a
// container. Stated plainly because this file said the opposite until v0.14.0,
// and a customer's security review is the wrong place to discover it.
//
// What the service does constrain:
//
//   - **Environment**: the child gets only the variables in the plugin's own
//     config — the service's environment, including its database and object
//     storage credentials, is not inherited
//   - **Process group**: each plugin runs in its own group, so a timeout kills
//     the whole tree rather than leaving orphans
//   - **Time**: bounded by `worker_pool.generation_timeout` (120s by default)
//   - **Concurrency**: bounded by `worker_pool.max_concurrent_generations`
//   - **Output size**: bounded by `registry.max_output_size`
//   - **Executable**: must live inside the configured plugins directory
//
// What it does **not** constrain: memory, CPU, filesystem access beyond the
// service account's own, and **network access** — a plugin can reach anything
// the service's pod can reach. Registering a plugin is therefore as privileged
// as running code on the host, and the write token that authorises it should be
// treated accordingly.
//
// ## Quick Start
//
// 1. Call `Plugins` to list available plugins
// 2. Build a `CodeGeneratorRequest` with your proto files
// 3. Call `GenerateCode` with the plugin name and request
// 4. Process the `CodeGeneratorResponse` with generated files
//
// ## Plugin Naming Convention
//
// Plugins are identified using the format: `<group>/<name>:<version>`
//
// Examples:
// - `protocolbuffers/go:v1.36.10` — Official Go protobuf plugin
// - `grpc/go:v1.5.1` — Official gRPC Go plugin
// - `grpc-ecosystem/gateway:v2.27.3` — gRPC-Gateway plugin
//
// Use `latest` as version to get the most recent version:
// - `protocolbuffers/go:latest`
type GeneratorAPIClient interface {
	// Generate code using a specified plugin.
	//
	// This method executes a protobuf code generation plugin and returns the generated files.
	// The plugin runs as a local child process under the limits described on the
	// service above — notably a time bound and an output-size bound, and notably
	// *not* a memory, CPU or network bound.
	//
	// This method is anonymous: it requires no credentials. Only the mutating
	// methods take a write token.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found in registry |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `RESOURCE_EXHAUSTED` | The service is at its concurrency limit; retry later |
	// | `UNAVAILABLE` | Object storage is unreachable, or the service is shutting down |
	// | `FAILED_PRECONDITION` | The plugin is registered but its archive is not in storage |
	// | `INTERNAL` | Plugin execution failed |
	// | `DEADLINE_EXCEEDED` | Plugin execution timeout |
	GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error)
	// List available plugins.
	//
	// Returns a list of all plugins registered in the service.
	// Use this to discover available plugins and their versions.
	Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsResponse, error)
	// Create a new plugin registration.
	//
	// Registers a plugin with the given group, name, version, optional config, and tags.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `ALREADY_EXISTS` | Plugin with same group/name/version exists |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `RESOURCE_EXHAUSTED` | Max plugins limit reached |
	// | `PERMISSION_DENIED` | Enterprise license required |
	CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*CreatePluginResponse, error)
	// Update an existing plugin.
	//
	// Replaces the config and tags of an existing plugin identified by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `PERMISSION_DENIED` | Enterprise license required |
	UpdatePlugin(ctx context.Context, in *UpdatePluginRequest, opts ...grpc.CallOption) (*UpdatePluginResponse, error)
	// Delete a plugin.
	//
	// Removes a plugin from the registry by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `PERMISSION_DENIED` | Enterprise license required |
	DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*DeletePluginResponse, error)
}

type generatorAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorAPIClient(cc grpc.ClientConnInterface) GeneratorAPIClient {
	return &generatorAPIClient{cc}
}

func (c *generatorAPIClient) GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCodeResponse)
	err := c.cc.Invoke(ctx, GeneratorAPI_GenerateCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAPIClient) Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginsResponse)
	err := c.cc.Invoke(ctx, GeneratorAPI_Plugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAPIClient) CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*CreatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePluginResponse)
	err := c.cc.Invoke(ctx, GeneratorAPI_CreatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAPIClient) UpdatePlugin(ctx context.Context, in *UpdatePluginRequest, opts ...grpc.CallOption) (*UpdatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePluginResponse)
	err := c.cc.Invoke(ctx, GeneratorAPI_UpdatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAPIClient) DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*DeletePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePluginResponse)
	err := c.cc.Invoke(ctx, GeneratorAPI_DeletePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorAPIServer is the server API for GeneratorAPI service.
// All implementations should embed UnimplementedGeneratorAPIServer
// for forward compatibility.
//
// # EasyP Code Generation Service
//
// This service provides a centralized API for executing protobuf/gRPC code generation plugins.
// Plugins are executed by the service, so every caller uses the same plugin version.
//
// ## Benefits
//
// - **Version Control**: All developers use the same plugin versions
// - **Zero Setup**: No local plugin installation required
// - **Auditability**: Centralized logging of all generation requests
//
// ## How plugins are executed
//
// A plugin is a binary the service runs as a local child process. It is not a
// container. Stated plainly because this file said the opposite until v0.14.0,
// and a customer's security review is the wrong place to discover it.
//
// What the service does constrain:
//
//   - **Environment**: the child gets only the variables in the plugin's own
//     config — the service's environment, including its database and object
//     storage credentials, is not inherited
//   - **Process group**: each plugin runs in its own group, so a timeout kills
//     the whole tree rather than leaving orphans
//   - **Time**: bounded by `worker_pool.generation_timeout` (120s by default)
//   - **Concurrency**: bounded by `worker_pool.max_concurrent_generations`
//   - **Output size**: bounded by `registry.max_output_size`
//   - **Executable**: must live inside the configured plugins directory
//
// What it does **not** constrain: memory, CPU, filesystem access beyond the
// service account's own, and **network access** — a plugin can reach anything
// the service's pod can reach. Registering a plugin is therefore as privileged
// as running code on the host, and the write token that authorises it should be
// treated accordingly.
//
// ## Quick Start
//
// 1. Call `Plugins` to list available plugins
// 2. Build a `CodeGeneratorRequest` with your proto files
// 3. Call `GenerateCode` with the plugin name and request
// 4. Process the `CodeGeneratorResponse` with generated files
//
// ## Plugin Naming Convention
//
// Plugins are identified using the format: `<group>/<name>:<version>`
//
// Examples:
// - `protocolbuffers/go:v1.36.10` — Official Go protobuf plugin
// - `grpc/go:v1.5.1` — Official gRPC Go plugin
// - `grpc-ecosystem/gateway:v2.27.3` — gRPC-Gateway plugin
//
// Use `latest` as version to get the most recent version:
// - `protocolbuffers/go:latest`
type GeneratorAPIServer interface {
	// Generate code using a specified plugin.
	//
	// This method executes a protobuf code generation plugin and returns the generated files.
	// The plugin runs as a local child process under the limits described on the
	// service above — notably a time bound and an output-size bound, and notably
	// *not* a memory, CPU or network bound.
	//
	// This method is anonymous: it requires no credentials. Only the mutating
	// methods take a write token.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found in registry |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `RESOURCE_EXHAUSTED` | The service is at its concurrency limit; retry later |
	// | `UNAVAILABLE` | Object storage is unreachable, or the service is shutting down |
	// | `FAILED_PRECONDITION` | The plugin is registered but its archive is not in storage |
	// | `INTERNAL` | Plugin execution failed |
	// | `DEADLINE_EXCEEDED` | Plugin execution timeout |
	GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error)
	// List available plugins.
	//
	// Returns a list of all plugins registered in the service.
	// Use this to discover available plugins and their versions.
	Plugins(context.Context, *PluginsRequest) (*PluginsResponse, error)
	// Create a new plugin registration.
	//
	// Registers a plugin with the given group, name, version, optional config, and tags.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `ALREADY_EXISTS` | Plugin with same group/name/version exists |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `RESOURCE_EXHAUSTED` | Max plugins limit reached |
	// | `PERMISSION_DENIED` | Enterprise license required |
	CreatePlugin(context.Context, *CreatePluginRequest) (*CreatePluginResponse, error)
	// Update an existing plugin.
	//
	// Replaces the config and tags of an existing plugin identified by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `INVALID_ARGUMENT` | Invalid plugin name format |
	// | `PERMISSION_DENIED` | Enterprise license required |
	UpdatePlugin(context.Context, *UpdatePluginRequest) (*UpdatePluginResponse, error)
	// Delete a plugin.
	//
	// Removes a plugin from the registry by group/name/version.
	// Requires an Enterprise license.
	//
	// ## Error Codes
	//
	// | Code | Description |
	// |------|-------------|
	// | `NOT_FOUND` | Plugin not found |
	// | `PERMISSION_DENIED` | Enterprise license required |
	DeletePlugin(context.Context, *DeletePluginRequest) (*DeletePluginResponse, error)
}

// UnimplementedGeneratorAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeneratorAPIServer struct{}

func (UnimplementedGeneratorAPIServer) GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCode not implemented")
}
func (UnimplementedGeneratorAPIServer) Plugins(context.Context, *PluginsRequest) (*PluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plugins not implemented")
}
func (UnimplementedGeneratorAPIServer) CreatePlugin(context.Context, *CreatePluginRequest) (*CreatePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlugin not implemented")
}
func (UnimplementedGeneratorAPIServer) UpdatePlugin(context.Context, *UpdatePluginRequest) (*UpdatePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlugin not implemented")
}
func (UnimplementedGeneratorAPIServer) DeletePlugin(context.Context, *DeletePluginRequest) (*DeletePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlugin not implemented")
}
func (UnimplementedGeneratorAPIServer) testEmbeddedByValue() {}

// UnsafeGeneratorAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratorAPIServer will
// result in compilation errors.
type UnsafeGeneratorAPIServer interface {
	mustEmbedUnimplementedGeneratorAPIServer()
}

func RegisterGeneratorAPIServer(s grpc.ServiceRegistrar, srv GeneratorAPIServer) {
	// If the following call panics, it indicates UnimplementedGeneratorAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeneratorAPI_ServiceDesc, srv)
}

func _GeneratorAPI_GenerateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAPIServer).GenerateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneratorAPI_GenerateCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAPIServer).GenerateCode(ctx, req.(*GenerateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAPI_Plugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAPIServer).Plugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneratorAPI_Plugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAPIServer).Plugins(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAPI_CreatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAPIServer).CreatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneratorAPI_CreatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAPIServer).CreatePlugin(ctx, req.(*CreatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAPI_UpdatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAPIServer).UpdatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneratorAPI_UpdatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAPIServer).UpdatePlugin(ctx, req.(*UpdatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAPI_DeletePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAPIServer).DeletePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneratorAPI_DeletePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAPIServer).DeletePlugin(ctx, req.(*DeletePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneratorAPI_ServiceDesc is the grpc.ServiceDesc for GeneratorAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneratorAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "easyp.generator.v1.GeneratorAPI",
	HandlerType: (*GeneratorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCode",
			Handler:    _GeneratorAPI_GenerateCode_Handler,
		},
		{
			MethodName: "Plugins",
			Handler:    _GeneratorAPI_Plugins_Handler,
		},
		{
			MethodName: "CreatePlugin",
			Handler:    _GeneratorAPI_CreatePlugin_Handler,
		},
		{
			MethodName: "UpdatePlugin",
			Handler:    _GeneratorAPI_UpdatePlugin_Handler,
		},
		{
			MethodName: "DeletePlugin",
			Handler:    _GeneratorAPI_DeletePlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "easyp/generator/v1/generator.proto",
}
